"""Optional quantum-neural policy for Dorabella candidates.

This is a variational quantum circuit used as an additional policy signal.
When enabled, it can also train itself with parameter-shift gradients from the
candidate memory generated by the solvers.
"""

from __future__ import annotations

import math
import random
from typing import Any

from .dorabella_memory_ai import candidate_features, feature_vector, sigmoid


def ensure_qnn(memory: dict[str, Any]) -> dict[str, Any]:
    active = memory.setdefault("active_memory", {})
    qnn = active.setdefault(
        "qnn",
        {
            "enabled": False,
            "qubits": 4,
            "layers": 4,
            "params": [],
            "updates": 0,
            "learning_rate": 0.015,
            "train_limit": 12,
            "last_loss": None,
            "training_history": [],
        },
    )
    qnn.setdefault("enabled", False)
    qnn.setdefault("qubits", 4)
    qnn.setdefault("layers", 4)
    if not valid_param_shape(qnn):
        qnn["params"] = init_qnn_params(int(qnn["qubits"]), int(qnn["layers"]))
    qnn.setdefault("updates", 0)
    qnn.setdefault("learning_rate", 0.015)
    qnn.setdefault("train_limit", 12)
    qnn.setdefault("last_loss", None)
    qnn.setdefault("training_history", [])
    return qnn


def valid_param_shape(qnn: dict[str, Any]) -> bool:
    params = qnn.get("params")
    qubits = int(qnn.get("qubits", 4))
    layers = int(qnn.get("layers", 4))
    return (
        isinstance(params, list)
        and len(params) == layers
        and all(isinstance(layer, list) and len(layer) == qubits * 2 for layer in params)
    )


def init_qnn_params(qubits: int, layers: int) -> list[list[float]]:
    rng = random.Random(1897 + qubits * 31 + layers * 17)
    scale = 0.25 / math.sqrt(max(qubits, 1))
    return [
        [rng.uniform(-scale, scale) for _ in range(qubits * 2)]
        for _ in range(layers)
    ]


def configure_qnn(
    memory: dict[str, Any],
    enabled: bool,
    qubits: int | None = None,
    layers: int | None = None,
    train_limit: int | None = None,
) -> dict[str, Any]:
    qnn = ensure_qnn(memory)
    qnn["enabled"] = bool(enabled)
    if qubits is not None:
        qnn["qubits"] = int(qubits)
    if layers is not None:
        qnn["layers"] = int(layers)
    if train_limit is not None:
        qnn["train_limit"] = int(train_limit)
    if not valid_param_shape(qnn):
        qnn["params"] = init_qnn_params(int(qnn["qubits"]), int(qnn["layers"]))
        qnn["updates"] = 0
    return qnn


def build_qnn_circuit(features: list[float], params: list[list[float]], qubits: int):
    try:
        from qiskit import QuantumCircuit
    except Exception as exc:  # pragma: no cover
        raise RuntimeError("Qiskit is required for QNN policy") from exc

    qc = QuantumCircuit(qubits)
    for q in range(qubits):
        val = features[q % len(features)]
        qc.ry(max(-math.pi, min(math.pi, val)) * 0.65, q)
        qc.rz(max(-math.pi, min(math.pi, val * 0.5)), q)
    for layer in params:
        for q in range(qubits - 1):
            qc.cx(q, q + 1)
        qc.cx(qubits - 1, 0)
        for q in range(qubits):
            qc.ry(layer[q], q)
            qc.rz(layer[q + qubits], q)
    return qc


def qnn_expectation(memory: dict[str, Any], candidate: dict[str, Any]) -> float:
    qnn = ensure_qnn(memory)
    if not qnn.get("enabled"):
        return 0.0
    try:
        from qiskit.quantum_info import Statevector
    except Exception:
        return 0.0

    signal = candidate_features(candidate)
    features = feature_vector(signal.features)
    qubits = int(qnn.get("qubits", 4))
    circuit = build_qnn_circuit(features, qnn["params"], qubits)
    state = Statevector.from_instruction(circuit)
    probs = state.probabilities_dict()
    expectation = 0.0
    for bitstring, prob in probs.items():
        # Qiskit bitstrings are big-endian here; use first bit as policy readout.
        z = 1.0 if bitstring[0] == "0" else -1.0
        expectation += z * float(prob)
    return max(-1.0, min(1.0, expectation))


def qnn_probability(memory: dict[str, Any], candidate: dict[str, Any]) -> float:
    return (qnn_expectation(memory, candidate) + 1.0) / 2.0


def expectation_from_features(
    features: list[float],
    params: list[list[float]],
    qubits: int,
) -> float:
    try:
        from qiskit.quantum_info import Statevector
    except Exception:
        return 0.0
    circuit = build_qnn_circuit(features, params, qubits)
    state = Statevector.from_instruction(circuit)
    probs = state.probabilities_dict()
    expectation = 0.0
    for bitstring, prob in probs.items():
        z = 1.0 if bitstring[0] == "0" else -1.0
        expectation += z * float(prob)
    return max(-1.0, min(1.0, expectation))


def qnn_train_candidate(memory: dict[str, Any], candidate: dict[str, Any]) -> dict[str, float]:
    qnn = ensure_qnn(memory)
    if not qnn.get("enabled"):
        return {"loss": 0.0, "prediction": 0.5, "target": 0.5}

    signal = candidate_features(candidate)
    target = sigmoid(signal.score)
    features = feature_vector(signal.features)
    qubits = int(qnn.get("qubits", 4))
    params = qnn["params"]
    lr = float(qnn.get("learning_rate", 0.015))

    base_expectation = expectation_from_features(features, params, qubits)
    pred = (base_expectation + 1.0) / 2.0
    loss = 0.5 * (pred - target) ** 2
    dloss_dexpectation = 0.5 * (pred - target)

    shift = math.pi / 2.0
    for layer_idx, layer in enumerate(params):
        for param_idx, value in enumerate(layer):
            plus = [row[:] for row in params]
            minus = [row[:] for row in params]
            plus[layer_idx][param_idx] = value + shift
            minus[layer_idx][param_idx] = value - shift
            exp_plus = expectation_from_features(features, plus, qubits)
            exp_minus = expectation_from_features(features, minus, qubits)
            grad_expectation = 0.5 * (exp_plus - exp_minus)
            layer[param_idx] -= lr * dloss_dexpectation * grad_expectation

    qnn["updates"] = int(qnn.get("updates", 0)) + 1
    qnn["last_loss"] = loss
    return {"loss": loss, "prediction": pred, "target": target}


def qnn_train_from_run(memory: dict[str, Any], run_record: dict[str, Any]) -> dict[str, Any]:
    qnn = ensure_qnn(memory)
    if not qnn.get("enabled"):
        return {"enabled": False, "trained": 0}
    candidates = list(run_record.get("partial_candidates", []))
    candidates.sort(key=lambda item: (item.get("resolved_unknowns", 0), item.get("score", -999)), reverse=True)
    train_limit = int(qnn.get("train_limit", 12))
    selected = candidates[:train_limit]
    losses = []
    for candidate in selected:
        result = qnn_train_candidate(memory, candidate)
        losses.append(result["loss"])
    summary = {
        "enabled": True,
        "trained": len(selected),
        "updates": qnn.get("updates", 0),
        "avg_loss": sum(losses) / max(len(losses), 1),
        "last_loss": qnn.get("last_loss"),
    }
    run_record["qnn_training"] = summary
    history = qnn.setdefault("training_history", [])
    history.append(
        {
            "run_started_at": run_record.get("started_at"),
            "trained": summary["trained"],
            "updates": summary["updates"],
            "avg_loss": summary["avg_loss"],
            "last_loss": summary["last_loss"],
        }
    )
    qnn["training_history"] = history[-100:]
    return summary
